[package]
name = "toymlrs-clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"

[dependencies.pyo3]
version = "0.23.2"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["abi3-py38"]