from typing import Optional

__version__: str = ...
"""The version of Toyml-RS."""

__all__: list[str] = ...

def sum_as_string(
        a: int,
        b: int,
) -> str: ...


class Kmeans:
    def __init__(self, k: int, max_iter: int,
                 centroids_init_method: str = "random",
                 distance_metric: str = "euclidean",
                 random_seed: Optional[int] = None,
                 ) -> None: ...
    def fit(self, point_values: list[list[float]]) -> None: ...
    def fit_predict(self, point_values: list[list[float]]) -> list[int]: ...
    @property
    def labels(self) -> list[int]: ...
