__version__: str = ...
"""The version of Toyml-RS."""

__all__: list[str] = ...

def sum_as_string(
        a: int,
        b: int,
) -> str: ...


class KmeansRust:
    def __init__(self, k: int) -> None: ...
    def fit(self, point_values: list[list[float]]) -> None: ...
    @property
    def labels(self) -> list[int]: ...
